import type { GpuClass, SpecTarget, UseCase } from "@/lib/types";

// ---------------------------------------------------------------------------
// Scoring rubric weights (must sum to 1.0). See README "Scoring" section.
// ---------------------------------------------------------------------------
export const RUBRIC_WEIGHTS = {
  use_case_fit: 0.3,
  price_performance: 0.25,
  build_reliability: 0.15,
  battery_portability: 0.1,
  display_comfort: 0.1,
  upgradeability: 0.05,
  local_availability: 0.05,
} as const;

// ---------------------------------------------------------------------------
// GPU class ordering, used to compare a laptop's gpu_tier to a target class.
// ---------------------------------------------------------------------------
export const GPU_CLASS_MIN_TIER: Record<GpuClass, number> = {
  integrated: 0,
  entry_dedicated: 3,
  mid_dedicated: 6,
  high_dedicated: 8,
};

// Rough brand reliability proxy (1..10). Used only as a tie-breaker / prior
// when a listing has no explicit build_quality. Intentionally conservative.
export const BRAND_RELIABILITY: Record<string, number> = {
  apple: 9,
  lenovo: 8,
  dell: 8,
  hp: 7,
  asus: 7,
  acer: 6,
  msi: 6,
  microsoft: 8,
  samsung: 7,
  huawei: 7,
  lg: 7,
};

export const DEFAULT_BRAND_RELIABILITY = 6;

// ---------------------------------------------------------------------------
// Use-case baseline spec targets.
// These power the no-API fallback engine AND are passed to the AI as guidance
// so the model anchors on realistic, non-overpowered specs.
// cpu_tier / gpu use the same normalized scales as LaptopSpecs.
// ---------------------------------------------------------------------------
interface UseCaseBaseline {
  minimum: SpecTarget;
  ideal: SpecTarget;
  unnecessary: string[];
}

const WINDOWS = "Windows 11";

export const USE_CASE_BASELINES: Record<UseCase, UseCaseBaseline> = {
  teaching: {
    minimum: {
      cpu_class: "Intel Core i3 (12th gen+) / Ryzen 3 5000+",
      cpu_tier: 4,
      ram_gb: 8,
      storage_gb: 256,
      storage_type: "SSD",
      gpu: "integrated",
      display_inch_min: 13,
      display_inch_max: 15.6,
      display_quality: "FHD IPS",
      battery_hours_min: 6,
      weight_kg_max: 1.8,
      os: WINDOWS,
      ports: ["HDMI", "USB-A", "USB-C"],
    },
    ideal: {
      cpu_class: "Intel Core i5 (12th gen+) / Ryzen 5 5000+",
      cpu_tier: 6,
      ram_gb: 16,
      storage_gb: 512,
      storage_type: "SSD",
      gpu: "integrated",
      display_inch_min: 14,
      display_inch_max: 15.6,
      display_quality: "FHD IPS",
      battery_hours_min: 9,
      weight_kg_max: 1.5,
      os: WINDOWS,
      ports: ["HDMI", "USB-A", "USB-C"],
    },
    unnecessary: [
      "كرت شاشة منفصل (مخصص للألعاب) — لا يفيد التدريس ويزيد السعر والوزن",
      "معالج i7/i9 — أقوى من حاجتك ويستهلك بطارية أكثر",
      "شاشة 4K — تستنزف البطارية بدون فائدة حقيقية للعرض والتدريس",
    ],
  },
  university: {
    minimum: {
      cpu_class: "Intel Core i5 (12th gen+) / Ryzen 5 5000+",
      cpu_tier: 5,
      ram_gb: 8,
      storage_gb: 256,
      storage_type: "SSD",
      gpu: "integrated",
      display_inch_min: 13,
      display_inch_max: 15.6,
      display_quality: "FHD IPS",
      battery_hours_min: 6,
      weight_kg_max: 1.8,
      os: WINDOWS,
    },
    ideal: {
      cpu_class: "Intel Core i5/i7 (12th gen+) / Ryzen 5/7 5000+",
      cpu_tier: 7,
      ram_gb: 16,
      storage_gb: 512,
      storage_type: "SSD",
      gpu: "entry_dedicated",
      display_inch_min: 14,
      display_inch_max: 15.6,
      display_quality: "FHD IPS",
      battery_hours_min: 8,
      weight_kg_max: 1.6,
      os: WINDOWS,
    },
    unnecessary: [
      "كرت شاشة عالي للألعاب — إلا إذا كان تخصصك تصميم أو هندسة ثقيلة",
      "تخزين 2 تيرابايت — غالباً 512GB تكفي مع التخزين السحابي",
    ],
  },
  office: {
    minimum: {
      cpu_class: "Intel Core i3 (12th gen+) / Ryzen 3 5000+",
      cpu_tier: 4,
      ram_gb: 8,
      storage_gb: 256,
      storage_type: "SSD",
      gpu: "integrated",
      display_inch_min: 13,
      display_inch_max: 15.6,
      display_quality: "FHD IPS",
      battery_hours_min: 6,
      weight_kg_max: 1.8,
      os: WINDOWS,
    },
    ideal: {
      cpu_class: "Intel Core i5 (12th gen+) / Ryzen 5 5000+",
      cpu_tier: 6,
      ram_gb: 16,
      storage_gb: 512,
      storage_type: "SSD",
      gpu: "integrated",
      display_inch_min: 14,
      display_inch_max: 15.6,
      display_quality: "FHD IPS",
      battery_hours_min: 9,
      weight_kg_max: 1.5,
      os: WINDOWS,
    },
    unnecessary: [
      "كرت شاشة منفصل — لا يفيد أعمال المكتب",
      "معالج i9 وذاكرة 32GB — مبالغة لأعمال أوفيس وتصفح",
    ],
  },
  programming: {
    minimum: {
      cpu_class: "Intel Core i5 (12th gen+) / Ryzen 5 5000+",
      cpu_tier: 6,
      ram_gb: 16,
      storage_gb: 512,
      storage_type: "SSD",
      gpu: "integrated",
      display_inch_min: 14,
      display_inch_max: 16,
      display_quality: "FHD IPS",
      battery_hours_min: 6,
      weight_kg_max: 1.9,
      os: WINDOWS,
    },
    ideal: {
      cpu_class: "Intel Core i7 (12th gen+) / Ryzen 7 5000+",
      cpu_tier: 8,
      ram_gb: 16,
      storage_gb: 512,
      storage_type: "SSD",
      gpu: "entry_dedicated",
      display_inch_min: 14,
      display_inch_max: 16,
      display_quality: "FHD IPS / 2K",
      battery_hours_min: 8,
      weight_kg_max: 1.6,
      os: WINDOWS,
    },
    unnecessary: [
      "كرت شاشة عالي للألعاب — إلا إذا كنت تعمل على الذكاء الاصطناعي محلياً",
      "شاشة 4K لامعة — تقلل البطارية وتتعب العين في البرمجة الطويلة",
    ],
  },
  design: {
    minimum: {
      cpu_class: "Intel Core i5 (12th gen+) / Ryzen 5 5000+",
      cpu_tier: 6,
      ram_gb: 16,
      storage_gb: 512,
      storage_type: "SSD",
      gpu: "entry_dedicated",
      display_inch_min: 14,
      display_inch_max: 16,
      display_quality: "FHD IPS بدقة ألوان جيدة (sRGB 100%)",
      battery_hours_min: 5,
      weight_kg_max: 2.0,
      os: WINDOWS,
    },
    ideal: {
      cpu_class: "Intel Core i7 (12th gen+) / Ryzen 7 5000+",
      cpu_tier: 8,
      ram_gb: 16,
      storage_gb: 1024,
      storage_type: "SSD",
      gpu: "mid_dedicated",
      display_inch_min: 15.6,
      display_inch_max: 16,
      display_quality: "2K/OLED بدقة ألوان عالية",
      battery_hours_min: 6,
      weight_kg_max: 1.8,
      os: WINDOWS,
    },
    unnecessary: [
      "أعلى كرت شاشة للألعاب — إلا للأعمال ثلاثية الأبعاد الثقيلة",
    ],
  },
  engineering: {
    minimum: {
      cpu_class: "Intel Core i5/i7 (12th gen+) / Ryzen 5/7 5000+",
      cpu_tier: 7,
      ram_gb: 16,
      storage_gb: 512,
      storage_type: "SSD",
      gpu: "entry_dedicated",
      display_inch_min: 15.6,
      display_inch_max: 16,
      display_quality: "FHD IPS",
      battery_hours_min: 4,
      weight_kg_max: 2.2,
      os: WINDOWS,
    },
    ideal: {
      cpu_class: "Intel Core i7 (12th gen+) / Ryzen 7 5000+",
      cpu_tier: 8,
      ram_gb: 32,
      storage_gb: 1024,
      storage_type: "SSD",
      gpu: "mid_dedicated",
      display_inch_min: 15.6,
      display_inch_max: 16,
      display_quality: "FHD/2K IPS",
      battery_hours_min: 5,
      weight_kg_max: 2.0,
      os: WINDOWS,
    },
    unnecessary: [
      "شاشة OLED لامعة — تطبيقات الهندسة لا تحتاجها وقد تسبب وميضاً",
    ],
  },
  gaming: {
    minimum: {
      cpu_class: "Intel Core i5 (12th gen+) / Ryzen 5 6000+",
      cpu_tier: 7,
      ram_gb: 16,
      storage_gb: 512,
      storage_type: "SSD",
      gpu: "mid_dedicated",
      display_inch_min: 15.6,
      display_inch_max: 16,
      display_quality: "FHD 144Hz",
      battery_hours_min: 3,
      weight_kg_max: 2.5,
      os: WINDOWS,
    },
    ideal: {
      cpu_class: "Intel Core i7 (13th gen+) / Ryzen 7 7000+",
      cpu_tier: 8,
      ram_gb: 16,
      storage_gb: 1024,
      storage_type: "SSD",
      gpu: "high_dedicated",
      display_inch_min: 15.6,
      display_inch_max: 16,
      display_quality: "FHD/2K 144Hz+",
      battery_hours_min: 4,
      weight_kg_max: 2.3,
      os: WINDOWS,
    },
    unnecessary: [
      "ذاكرة 64GB — نادراً ما تستفيد منها الألعاب",
      "شاشة 4K على جهاز محمول — تخفض الإطارات بشدة",
    ],
  },
  video_editing: {
    minimum: {
      cpu_class: "Intel Core i7 (12th gen+) / Ryzen 7 5000+",
      cpu_tier: 8,
      ram_gb: 16,
      storage_gb: 512,
      storage_type: "SSD",
      gpu: "mid_dedicated",
      display_inch_min: 15.6,
      display_inch_max: 16,
      display_quality: "FHD IPS بدقة ألوان جيدة",
      battery_hours_min: 4,
      weight_kg_max: 2.2,
      os: WINDOWS,
    },
    ideal: {
      cpu_class: "Intel Core i7/i9 (13th gen+) / Ryzen 7/9 7000+",
      cpu_tier: 9,
      ram_gb: 32,
      storage_gb: 1024,
      storage_type: "SSD",
      gpu: "high_dedicated",
      display_inch_min: 15.6,
      display_inch_max: 16,
      display_quality: "2K/4K بدقة ألوان عالية",
      battery_hours_min: 5,
      weight_kg_max: 2.0,
      os: WINDOWS,
    },
    unnecessary: [],
  },
  business: {
    minimum: {
      cpu_class: "Intel Core i5 (12th gen+) / Ryzen 5 5000+",
      cpu_tier: 5,
      ram_gb: 8,
      storage_gb: 256,
      storage_type: "SSD",
      gpu: "integrated",
      display_inch_min: 13,
      display_inch_max: 15.6,
      display_quality: "FHD IPS",
      battery_hours_min: 8,
      weight_kg_max: 1.5,
      os: WINDOWS,
    },
    ideal: {
      cpu_class: "Intel Core i7 (12th gen+) / Ryzen 7 5000+",
      cpu_tier: 7,
      ram_gb: 16,
      storage_gb: 512,
      storage_type: "SSD",
      gpu: "integrated",
      display_inch_min: 14,
      display_inch_max: 14,
      display_quality: "FHD IPS",
      battery_hours_min: 11,
      weight_kg_max: 1.3,
      os: WINDOWS,
    },
    unnecessary: [
      "كرت شاشة منفصل — يقلل البطارية ويزيد الوزن دون فائدة لأعمال الأعمال",
    ],
  },
  family: {
    minimum: {
      cpu_class: "Intel Core i3 (12th gen+) / Ryzen 3 5000+",
      cpu_tier: 3,
      ram_gb: 8,
      storage_gb: 256,
      storage_type: "SSD",
      gpu: "integrated",
      display_inch_min: 14,
      display_inch_max: 15.6,
      display_quality: "FHD",
      battery_hours_min: 5,
      weight_kg_max: 2.0,
      os: WINDOWS,
    },
    ideal: {
      cpu_class: "Intel Core i5 (12th gen+) / Ryzen 5 5000+",
      cpu_tier: 5,
      ram_gb: 8,
      storage_gb: 512,
      storage_type: "SSD",
      gpu: "integrated",
      display_inch_min: 15.6,
      display_inch_max: 15.6,
      display_quality: "FHD IPS",
      battery_hours_min: 7,
      weight_kg_max: 1.8,
      os: WINDOWS,
    },
    unnecessary: [
      "مواصفات احترافية عالية — الاستخدام العائلي لا يحتاجها",
    ],
  },
};
